import { test, expect, type Page } from './fixtures';
import { mkdtemp, mkdir, realpath, readFile, rm, symlink, writeFile } from 'node:fs/promises';
import { join, basename } from 'node:path';
import { tmpdir } from 'node:os';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const exec = promisify(execFile);
let workspace: string, session: { id: string }, created: string[];
const git = (...args: string[]) => exec('git', args, { cwd: workspace });
test.beforeEach(async ({ request }) => {
  workspace = await realpath(await mkdtemp(join(tmpdir(), 'litespeed-worktree-ui-'))); created = [];
  await git('init', '-b', 'main'); await git('config', 'user.name', 'Fixture'); await git('config', 'user.email', 'fixture@local');
  await writeFile(join(workspace, 'notes.md'), '# A quiet workspace\n'); await git('add', '.'); await git('commit', '-m', 'Initial');
  session = await (await request.post('/api/sessions', { data: { workspace, title: 'My local project', providerId: 'fixture', model: 'test-model', architecture: null } })).json();
});
test.afterEach(async ({ request }) => {
  for (const id of [session.id, ...created]) await request.delete(`/api/sessions/${id}`);
  const records = (await (await request.get(`/api/worktrees?workspace=${encodeURIComponent(workspace)}`)).json()).worktrees;
  for (const record of records) { const result = await request.post(`/api/worktrees/${record.id}/remove/prepare`, { data: {} }); if (result.ok()) await request.post(`/api/worktrees/${record.id}/remove`, { data: { planId: (await result.json()).id } }); }
  await rm(workspace, { recursive: true, force: true });
});
async function open(page: Page) {
  await page.goto(`/#session/${session.id}`);
  if ((page.viewportSize()?.width ?? 1440) < 750) await page.getByRole('button', { name: 'Open navigation', exact: true }).click();
  await page.getByRole('button', { name: `Working copies for ${basename(workspace)}`, exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Working copies', exact: true })).toBeVisible();
}
async function review(page: Page, name = 'Refine the browser', includeLocalEdits = false, includeLocalSetup = false) {
  await page.getByRole('button', { name: 'New worktree', exact: true }).click();
  await page.getByRole('textbox', { name: 'Worktree task name' }).fill(name);
  if (includeLocalEdits) await page.getByRole('checkbox', { name: /Include local edits/ }).check();
  if (includeLocalSetup) await page.getByRole('checkbox', { name: /Include local setup/ }).check();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Create worktree?' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Create and open', exact: true })).toBeFocused();
}
async function create(page: Page) {
  await page.getByRole('button', { name: 'Create and open', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page.getByRole('button', { name: 'Manage task worktree' })).toBeVisible();
  const id = page.url().match(/session\/([^/]+)$/)![1]; created.push(id); return id;
}
async function reviewTaskMove(page: Page) {
  await page.getByRole('button', { name: 'Session actions', exact: true }).click();
  await page.getByRole('button', { name: 'Continue in worktree', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Continue in a worktree', exact: true });
  await expect(dialog.getByRole('textbox', { name: 'Working copy name' })).toBeFocused();
  await dialog.getByRole('button', { name: 'Continue', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Move task to worktree?', exact: true }).getByRole('button', { name: 'Move task', exact: true })).toBeFocused();
}
test('moves the existing conversation and draft into its own files without changing the original project', async ({ page, request }) => {
  await page.emulateMedia({ colorScheme: 'dark' }); await page.goto(`/#session/${session.id}`);
  const composer = page.getByRole('textbox', { name: 'Message Litespeed' }); await composer.fill('create fixture before moving my task'); await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await page.getByRole('region', { name: 'Permission requested' }).getByRole('button', { name: 'Allow once', exact: true }).click();
  await expect.poll(async () => (await (await request.get(`/api/sessions/${session.id}`)).json()).session.status).toBe('idle');
  await git('add', 'result.txt'); await writeFile(join(workspace, 'notes.md'), '# Keep this local edit\n');
  const sourceStatus = (await git('status', '--porcelain=v1')).stdout, messages = (await (await request.get(`/api/sessions/${session.id}`)).json()).messages;
  await composer.fill('My next step stays in the composer'); const before = (await (await request.get('/fixture/requests')).json()).count;
  const settings = await (await request.get('/api/settings')).json(), previewUrl = settings.providers.find((provider: { id: string }) => provider.id === 'fixture').baseUrl + '/browser-inspector';
  expect((await request.post(`/api/sessions/${session.id}/browser`, { data: { action: 'open', url: previewUrl } })).ok()).toBe(true);
  const browserBefore = await (await request.get(`/api/sessions/${session.id}/browser`)).json();
  if (!await page.getByRole('tab', { name: 'Files', exact: true }).isVisible()) await page.getByRole('button', { name: 'Show workspace panel' }).click();
  await page.getByRole('tab', { name: 'Files', exact: true }).click();
  const browseFiles = page.getByRole('button', { name: 'Browse files', exact: true }); if (await browseFiles.isVisible()) await browseFiles.click();
  await page.locator('.file-list').getByRole('button', { name: 'notes.md', exact: true }).click();
  await expect(page.getByRole('tab', { name: 'notes.md', exact: true })).toBeVisible();
  await reviewTaskMove(page); await page.screenshot({ path: '.ui-audit/task-worktree-review-desktop.png', animations: 'disabled' });
  await page.getByRole('button', { name: 'Move task', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page).toHaveURL(new RegExp(`#session/${session.id}$`)); await expect(page.getByRole('button', { name: 'Manage task worktree' })).toBeVisible();
  await expect(composer).toHaveValue('My next step stays in the composer');
  await expect(page.getByRole('tab', { name: 'notes.md', exact: true })).toHaveAttribute('aria-selected', 'true');
  const moved = await (await request.get(`/api/sessions/${session.id}`)).json(); expect(moved.session.workspace).not.toBe(workspace); expect(moved.messages.slice(0, -1)).toEqual(messages);
  expect(await readFile(join(moved.session.workspace, 'notes.md'), 'utf8')).toBe('# Keep this local edit\n'); expect((await git('status', '--porcelain=v1')).stdout).toBe(sourceStatus);
  expect((await exec('git', ['show', ':result.txt'], { cwd: moved.session.workspace })).stdout).toBe(await readFile(join(workspace, 'result.txt'), 'utf8'));
  expect((await (await request.get('/fixture/requests')).json()).count).toBe(before);
  const browserAfter = await (await request.get(`/api/sessions/${session.id}/browser`)).json(); expect(browserAfter.tabs.map((tab: { id: string; url: string }) => [tab.id, tab.url])).toEqual(browserBefore.tabs.map((tab: { id: string; url: string }) => [tab.id, tab.url]));
  await page.getByRole('button', { name: 'Session actions', exact: true }).click(); await expect(page.getByRole('button', { name: 'Undo last turn', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Close session actions', exact: true }).click(); await page.reload(); await expect(composer).toHaveValue('My next step stays in the composer');
  await expect(page.getByRole('tab', { name: 'notes.md', exact: true })).toHaveAttribute('aria-selected', 'true');
  await expect(page.getByRole('heading', { name: 'Keep this local edit' })).toBeVisible();
  await expect(page.locator('.workspace-move-message')).not.toHaveAttribute('open');
  await page.screenshot({ path: '.ui-audit/task-worktree-moved-desktop.png', animations: 'disabled' });
});
test('refreshes a stale task move in a narrow window without losing the draft', async ({ page, request }) => {
  await page.setViewportSize({ width: 390, height: 500 }); await page.emulateMedia({ colorScheme: 'light' }); await page.goto(`/#session/${session.id}`);
  await page.getByRole('textbox', { name: 'Message Litespeed' }).fill('Continue when the new copy is ready');
  await reviewTaskMove(page); await expect(page.getByRole('button', { name: 'Move task', exact: true })).toBeInViewport();
  await writeFile(join(workspace, 'notes.md'), '# A more recent edit\n');
  await page.getByRole('button', { name: 'Move task', exact: true }).click(); await expect(page.getByRole('dialog').getByRole('alert')).toContainText('changed after review');
  await page.getByRole('button', { name: 'Refresh review', exact: true }).click(); await expect(page.getByRole('button', { name: 'Move task', exact: true })).toBeFocused();
  await page.screenshot({ path: '.ui-audit/task-worktree-review-mobile.png', animations: 'disabled' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Move task', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('textbox', { name: 'Message Litespeed' })).toHaveValue('Continue when the new copy is ready');
  const moved = await (await request.get(`/api/sessions/${session.id}`)).json(); expect(await readFile(join(moved.session.workspace, 'notes.md'), 'utf8')).toBe('# A more recent edit\n');
});
test('dismisses a task move review without changing its workspace or draft', async ({ page, request }) => {
  await page.goto(`/#session/${session.id}`);
  await page.getByRole('textbox', { name: 'Message Litespeed' }).fill('Keep working here');
  await reviewTaskMove(page); await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Session actions', exact: true })).toBeFocused();
  await expect(page.getByRole('textbox', { name: 'Message Litespeed' })).toHaveValue('Keep working here');
  expect((await (await request.get(`/api/sessions/${session.id}`)).json()).session.workspace).toBe(workspace);
  expect((await (await request.get(`/api/worktrees?workspace=${encodeURIComponent(workspace)}`)).json()).worktrees).toEqual([]);
});

test('opens historical absolute links, tools and snapshots in the current folder across both moves', async ({ page, request }) => {
  const original = await readFile(join(workspace, 'notes.md'), 'utf8');
  const sent = await request.post(`/api/sessions/${session.id}/messages`, { data: { content: `RULES_BROWSER READ_PATH[${workspace}/notes.md]\n\n[Earlier notes](${workspace}/notes.md)`, attachments: [{ name: 'notes.md', path: join(workspace, 'notes.md') }] } });
  expect(sent.ok()).toBe(true); await expect.poll(async () => (await (await request.get(`/api/sessions/${session.id}`)).json()).session.status).toBe('idle');
  await page.goto(`/#session/${session.id}`); await reviewTaskMove(page); await page.getByRole('button', { name: 'Move task', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0);
  const moved = await (await request.get(`/api/sessions/${session.id}`)).json();
  await writeFile(join(moved.session.workspace, 'notes.md'), '# The current worktree version\n');
  await page.getByRole('link', { name: 'Earlier notes', exact: true }).click(); await expect(page.getByRole('heading', { name: 'The current worktree version' })).toBeVisible();
  expect(await readFile(join(workspace, 'notes.md'), 'utf8')).toBe(original);
  await page.getByRole('button', { name: 'Close notes.md', exact: true }).click();
  await page.locator('.work-log > summary').first().click(); await page.locator('.tool-card > summary').first().click();
  await page.getByRole('button', { name: 'Open in workspace', exact: true }).click(); await expect(page.getByRole('heading', { name: 'The current worktree version' })).toBeVisible();
  await page.getByRole('button', { name: 'Preview notes.md', exact: true }).click();
  await expect(page.getByLabel('Contents of notes.md')).toHaveText(original.trim());
  await page.getByRole('button', { name: 'Open current file', exact: true }).click(); await expect(page.getByRole('heading', { name: 'The current worktree version' })).toBeVisible();
  await page.getByRole('button', { name: 'Session actions', exact: true }).click(); await page.getByRole('button', { name: 'Continue locally', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Continue locally', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0);
  await writeFile(join(workspace, 'notes.md'), '# The latest local version\n'); await page.reload();
  await page.getByRole('link', { name: 'Earlier notes', exact: true }).click(); await expect(page.getByRole('heading', { name: 'The latest local version' })).toBeVisible();
  await page.getByRole('button', { name: 'Close notes.md', exact: true }).click();
  await page.locator('.work-log > summary').first().click(); await page.locator('.tool-card > summary').first().click();
  await page.getByRole('button', { name: 'Open in workspace', exact: true }).click(); await expect(page.getByRole('heading', { name: 'The latest local version' })).toBeVisible();
  await page.getByRole('button', { name: 'Preview notes.md', exact: true }).click(); await expect(page.getByLabel('Contents of notes.md')).toHaveText(original.trim());
  await page.getByRole('button', { name: 'Open current file', exact: true }).click(); await expect(page.getByRole('heading', { name: 'The latest local version' })).toBeVisible();
  expect(await readFile(join(moved.session.workspace, 'notes.md'), 'utf8')).toBe('# The current worktree version\n');
});
test('creates and reopens a worktree task with a clear starting point and preserved source draft', async ({ page, request }) => {
  await page.emulateMedia({ colorScheme: 'dark' }); await writeFile(join(workspace, 'notes.md'), '# Local edits stay here\n');
  await page.goto(`/#session/${session.id}`); await page.getByRole('textbox', { name: 'Message Litespeed' }).fill('Keep this local draft');
  const preferences = await (await request.get(`/api/workspace-preferences?workspace=${encodeURIComponent(workspace)}`)).json(), before = (await (await request.get('/fixture/requests')).json()).count;
  await open(page); await review(page); await expect(page.getByText(/1 changed file stays/)).toBeVisible();
  await mkdir('.ui-audit', { recursive: true }); await page.screenshot({ path: '.ui-audit/worktree-create-desktop.png', animations: 'disabled' });
  const id = await create(page), detail = await (await request.get(`/api/sessions/${id}`)).json();
  expect(detail.session.workspace).not.toBe(workspace); expect(detail.session.worktree.project).toBe(workspace); expect(detail.messages).toEqual([]);
  expect(await readFile(join(detail.session.workspace, 'notes.md'), 'utf8')).toBe('# A quiet workspace\n'); expect(await readFile(join(workspace, 'notes.md'), 'utf8')).toBe('# Local edits stay here\n');
  expect((await (await request.get('/fixture/requests')).json()).count).toBe(before); expect(await (await request.get(`/api/workspace-preferences?workspace=${encodeURIComponent(workspace)}`)).json()).toEqual(preferences);
  await expect(page.locator('.session-group').filter({ has: page.getByRole('button', { name: `Working copies for ${basename(workspace)}` }) }).locator('.session-link').filter({ hasText: 'Refine the browser' })).toBeVisible();
  await page.screenshot({ path: '.ui-audit/worktree-task-desktop.png', animations: 'disabled' });
  await page.reload(); await expect(page.getByRole('button', { name: 'Manage task worktree' })).toBeVisible(); await page.getByRole('button', { name: 'Manage task worktree' }).click();
  await expect(page.getByRole('button', { name: 'Open worktree Refine-the-browser' })).toBeVisible(); await page.screenshot({ path: '.ui-audit/worktree-list-desktop.png', animations: 'disabled' });
  await page.getByRole('button', { name: 'Open worktree Refine-the-browser' }).click(); await expect(page).toHaveURL(new RegExp(`#session/${id}$`));
  await page.goto(`/#session/${session.id}`); await expect(page.getByRole('textbox', { name: 'Message Litespeed' })).toHaveValue('Keep this local draft');
});
test('rechecks cleanup and keeps task history and branch after removing a clean copy', async ({ page, request }) => {
  await open(page); await review(page, 'Review changes'); const id = await create(page), detail = await (await request.get(`/api/sessions/${id}`)).json(), worktree = detail.session.worktree;
  await page.getByRole('button', { name: 'Manage task worktree' }).click();
  await writeFile(join(detail.session.workspace, 'local.txt'), 'Keep me'); await page.getByRole('button', { name: 'Remove worktree Review-changes', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('untracked'); expect(await readFile(join(detail.session.workspace, 'local.txt'), 'utf8')).toBe('Keep me');
  await rm(join(detail.session.workspace, 'local.txt')); await page.getByRole('button', { name: 'Remove worktree Review-changes', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Remove working copy?' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Cancel', exact: true })).toBeFocused();
  await page.screenshot({ path: '.ui-audit/worktree-remove-desktop.png', animations: 'disabled' });
  await page.getByRole('button', { name: 'Remove working copy', exact: true }).click(); await expect(page.getByRole('dialog', { name: 'Working copies', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Open worktree Review-changes' })).toHaveCount(0); await page.getByRole('button', { name: 'Close dialog' }).click();
  await expect(page.locator('.worktree-unavailable')).toContainText('Your conversation is saved'); await expect(page.getByRole('textbox', { name: 'Message Litespeed' })).toBeDisabled();
  expect((await (await request.get(`/api/sessions/${id}`)).json()).session.worktree.removed).toBe(true); expect((await git('rev-parse', worktree.branch)).stdout.trim()).toBe(worktree.head);
  await page.reload(); await expect(page.locator('.worktree-unavailable')).toContainText('Your conversation is saved'); await page.getByRole('button', { name: 'Open project', exact: true }).click();
  await expect(page.getByRole('textbox', { name: 'Message Litespeed' })).toBeEnabled();
});
test('restores the last saved files and the same task draft after branch deletion', async ({ page, request }) => {
  await page.emulateMedia({ colorScheme: 'dark' }); await open(page); await review(page, 'A saved idea'); const id = await create(page);
  const detail = await (await request.get(`/api/sessions/${id}`)).json();
  const other = await (await request.post(`/api/worktrees/${detail.session.worktree.id}/tasks`, { data: { providerId: 'fixture', model: 'test-model' } })).json(); created.push(other.id);
  await writeFile(join(detail.session.workspace, 'notes.md'), '# The idea is ready to continue\n');
  await exec('git', ['add', '.'], { cwd: detail.session.workspace }); await exec('git', ['commit', '-m', 'Save idea'], { cwd: detail.session.workspace });
  await page.getByRole('textbox', { name: 'Message Litespeed' }).fill('Keep this draft with my task');
  await page.getByRole('button', { name: 'Manage task worktree' }).click(); await page.getByRole('button', { name: 'Remove worktree A-saved-idea', exact: true }).click();
  await page.getByRole('button', { name: 'Remove working copy', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Restore worktree A-saved-idea' })).toBeVisible();
  await page.screenshot({ path: '.ui-audit/worktree-saved-desktop.png', animations: 'disabled' });
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
  await git('branch', '-D', detail.session.worktree.branch);
  const before = (await (await request.get('/fixture/requests')).json()).count;
  await page.locator('.worktree-unavailable').getByRole('button', { name: 'Restore working copy', exact: true }).click();
  const restoration = page.getByRole('dialog', { name: 'Restore working copy?', exact: true });
  await expect(restoration).toBeVisible();
  await expect(restoration.getByRole('button', { name: 'Restore working copy', exact: true })).toBeFocused();
  await page.screenshot({ path: '.ui-audit/worktree-restore-desktop.png', animations: 'disabled' });
  await restoration.getByRole('button', { name: 'Restore working copy', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page).toHaveURL(new RegExp(`#session/${id}$`));
  await expect(page.getByRole('textbox', { name: 'Message Litespeed' })).toBeEnabled(); await expect(page.getByRole('textbox', { name: 'Message Litespeed' })).toHaveValue('Keep this draft with my task');
  expect(await readFile(join(detail.session.workspace, 'notes.md'), 'utf8')).toBe('# The idea is ready to continue\n');
  expect((await (await request.get('/fixture/requests')).json()).count).toBe(before); expect((await (await request.get(`/api/sessions/${id}`)).json()).messages).toEqual([]);
  await page.reload(); await expect(page.getByRole('textbox', { name: 'Message Litespeed' })).toHaveValue('Keep this draft with my task');
});
test('restoration review fits a short window and preserves files that appear after review', async ({ page, request }) => {
  await page.setViewportSize({ width: 390, height: 500 }); await page.emulateMedia({ colorScheme: 'light' });
  await open(page); await review(page, 'A saved idea with a detailed name'); const id = await create(page);
  const detail = await (await request.get(`/api/sessions/${id}`)).json(), worktree = detail.session.worktree;
  const removal = await (await request.post(`/api/worktrees/${worktree.id}/remove/prepare`, { data: {} })).json(); await request.post(`/api/worktrees/${worktree.id}/remove`, { data: { planId: removal.id } });
  await page.locator('.worktree-unavailable').getByRole('button', { name: 'Restore working copy', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Restore working copy?', exact: true });
  await expect(dialog.getByRole('button', { name: 'Restore working copy', exact: true })).toBeInViewport();
  await page.screenshot({ path: '.ui-audit/worktree-restore-mobile.png', animations: 'disabled' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await mkdir(detail.session.workspace); await writeFile(join(detail.session.workspace, 'keep.txt'), 'New user file');
  await dialog.getByRole('button', { name: 'Restore working copy', exact: true }).click();
  await expect(dialog.getByRole('alert')).toContainText('already present'); expect(await readFile(join(detail.session.workspace, 'keep.txt'), 'utf8')).toBe('New user file');
  await rm(detail.session.workspace, { recursive: true }); await dialog.getByRole('button', { name: 'Refresh review', exact: true }).click();
  await expect(dialog.getByRole('button', { name: 'Restore working copy', exact: true })).toBeFocused();
  await dialog.getByRole('button', { name: 'Restore working copy', exact: true }).click(); await expect(dialog).toHaveCount(0);
  await expect(page.getByRole('textbox', { name: 'Message Litespeed' })).toBeEnabled();
});
test('working copy creation and review fit a narrow screen', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await open(page); await review(page, 'A detailed task name for a narrow screen');
  await expect(page.getByRole('button', { name: 'Create and open', exact: true })).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: '.ui-audit/worktree-create-mobile.png', animations: 'disabled' });
  await create(page); await page.getByRole('button', { name: 'Manage task worktree' }).click();
  await expect(page.getByRole('button', { name: /Open worktree A-detailed/ })).toBeInViewport(); await page.screenshot({ path: '.ui-audit/worktree-list-mobile.png', animations: 'disabled' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.keyboard.press('Escape'); await expect(page.getByRole('button', { name: 'Manage task worktree' })).toBeFocused();
});
test('reviews and copies local edits with staging intact while keeping the original draft', async ({ page, request }) => {
  await page.emulateMedia({ colorScheme: 'dark' });
  await writeFile(join(workspace, 'notes.md'), '# Staged notes\n'); await git('add', 'notes.md'); await writeFile(join(workspace, 'notes.md'), '# Working notes\n');
  await mkdir(join(workspace, 'design')); await writeFile(join(workspace, 'design', 'interaction-notes.md'), 'A new note\n');
  await page.goto(`/#session/${session.id}`); await page.getByRole('textbox', { name: 'Message Litespeed' }).fill('Keep this draft in my local project.');
  await open(page); await review(page, 'Continue these edits', true);
  const dialog = page.getByRole('dialog'); await dialog.locator('.worktree-copy-files summary').click();
  await expect(dialog).toContainText('2 files with local edits'); await expect(dialog).toContainText('design/interaction-notes.md');
  await page.screenshot({ path: '.ui-audit/worktree-copy-review-desktop.png', animations: 'disabled' });
  const id = await create(page), detail = await (await request.get(`/api/sessions/${id}`)).json();
  expect(await readFile(join(detail.session.workspace, 'notes.md'), 'utf8')).toBe('# Working notes\n');
  expect((await exec('git', ['show', ':notes.md'], { cwd: detail.session.workspace })).stdout).toBe('# Staged notes\n');
  expect(await readFile(join(detail.session.workspace, 'design', 'interaction-notes.md'), 'utf8')).toBe('A new note\n');
  expect(await readFile(join(workspace, 'notes.md'), 'utf8')).toBe('# Working notes\n'); expect((await git('show', ':notes.md')).stdout).toBe('# Staged notes\n');
  await page.goto(`/#session/${session.id}`); await expect(page.getByRole('textbox', { name: 'Message Litespeed' })).toHaveValue('Keep this draft in my local project.');
});
test('refreshes a stale local-edit review and keeps all controls reachable in a short window', async ({ page, request }) => {
  await page.setViewportSize({ width: 390, height: 500 }); await page.emulateMedia({ colorScheme: 'light' });
  await writeFile(join(workspace, 'notes.md'), 'Reviewed notes'); await open(page);
  await page.getByRole('button', { name: 'New worktree', exact: true }).click(); await page.getByRole('textbox', { name: 'Worktree task name' }).fill('Carry my edits forward');
  await page.getByRole('checkbox', { name: /Include local edits/ }).check();
  await page.screenshot({ path: '.ui-audit/worktree-copy-form-mobile.png', animations: 'disabled' });
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Create worktree?' })).toBeVisible();
  await writeFile(join(workspace, 'notes.md'), 'New notes since review');
  await page.getByRole('button', { name: 'Create and open', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('changed after review');
  await page.getByRole('button', { name: 'Refresh review', exact: true }).click(); await expect(page.getByRole('alert')).toHaveCount(0); await expect(page.getByRole('button', { name: 'Create and open', exact: true })).toBeFocused();
  await page.getByRole('dialog').locator('.worktree-copy-files summary').click();
  await page.getByRole('button', { name: 'Create and open', exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: '.ui-audit/worktree-copy-review-mobile.png', animations: 'disabled' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const id = await create(page), detail = await (await request.get(`/api/sessions/${id}`)).json();
  expect(await readFile(join(detail.session.workspace, 'notes.md'), 'utf8')).toBe('New notes since review');
});
test('reviews setup filenames without showing their contents, skips linked files and creates a configured working copy', async ({ page, request }) => {
  await page.emulateMedia({ colorScheme: 'dark' });
  await writeFile(join(workspace, '.gitignore'), '.env*\n'); await writeFile(join(workspace, '.worktreeinclude'), '.env*\n'); await git('add', '.'); await git('commit', '-m', 'Setup selection');
  await writeFile(join(workspace, '.env'), 'LOCAL_SETUP_FIXTURE=private-value\n'); await symlink('notes.md', join(workspace, '.env.link'));
  await writeFile(join(workspace, 'notes.md'), 'Current local notes');
  await open(page); await review(page, 'A ready-to-use working copy', true, true);
  const dialog = page.getByRole('dialog'); await dialog.locator('.worktree-setup-files summary').click();
  await expect(dialog).toContainText('1 local setup file'); await expect(dialog).toContainText('1 skipped'); await expect(dialog).toContainText('.env.link'); await expect(dialog).not.toContainText('LOCAL_SETUP_FIXTURE');
  await page.screenshot({ path: '.ui-audit/worktree-setup-review-desktop.png', animations: 'disabled' });
  const id = await create(page), detail = await (await request.get(`/api/sessions/${id}`)).json();
  expect(await readFile(join(detail.session.workspace, '.env'), 'utf8')).toBe('LOCAL_SETUP_FIXTURE=private-value\n'); expect(await readFile(join(detail.session.workspace, 'notes.md'), 'utf8')).toBe('Current local notes');
  await expect(readFile(join(detail.session.workspace, '.env.link'))).rejects.toMatchObject({ code: 'ENOENT' });
});
test('keeps the setup-file review readable on a short narrow screen and refreshes changed configuration', async ({ page, request }) => {
  await page.setViewportSize({ width: 390, height: 500 }); await page.emulateMedia({ colorScheme: 'light' });
  await writeFile(join(workspace, '.gitignore'), '.env*\n'); await writeFile(join(workspace, '.worktreeinclude'), '.env*\n'); await git('add', '.'); await git('commit', '-m', 'Setup selection');
  await writeFile(join(workspace, '.env'), 'Original fixture'); await open(page); await review(page, 'Continue with local setup', false, true);
  await writeFile(join(workspace, '.env'), 'Updated fixture'); await page.getByRole('button', { name: 'Create and open', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('changed after review');
  await page.getByRole('button', { name: 'Refresh review', exact: true }).click(); await expect(page.getByRole('alert')).toHaveCount(0); await expect(page.getByRole('button', { name: 'Create and open', exact: true })).toBeFocused();
  await page.getByRole('dialog').locator('.worktree-setup-files summary').click();
  await page.getByRole('button', { name: 'Create and open', exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: '.ui-audit/worktree-setup-review-mobile.png', animations: 'disabled' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const id = await create(page), detail = await (await request.get(`/api/sessions/${id}`)).json(); expect(await readFile(join(detail.session.workspace, '.env'), 'utf8')).toBe('Updated fixture');
});
test('chooses a starting branch by keyboard without switching the source or copying its unrelated edits', async ({ page, request }) => {
  await page.emulateMedia({ colorScheme: 'dark' });
  await git('switch', '-c', 'feature/refine-the-preview'); await writeFile(join(workspace, 'notes.md'), 'Feature branch notes'); await git('commit', '-am', 'Feature notes'); await git('switch', 'main');
  await writeFile(join(workspace, 'notes.md'), 'Current local work');
  await open(page); await page.getByRole('button', { name: 'New worktree', exact: true }).click(); await page.getByRole('textbox', { name: 'Worktree task name' }).fill('Continue the feature');
  await page.getByRole('checkbox', { name: /Include local edits/ }).check();
  await page.getByRole('button', { name: /^Choose starting branch/ }).click(); const search = page.getByRole('textbox', { name: 'Search starting branches' }); await expect(search).toBeFocused(); await search.fill('refine');
  await expect(page.getByRole('option', { name: /feature\/refine-the-preview/ })).toBeVisible();
  await page.screenshot({ path: '.ui-audit/worktree-starting-picker-desktop.png', animations: 'disabled' });
  await page.keyboard.press('ArrowDown'); await expect(page.getByRole('option', { name: /feature\/refine-the-preview/ })).toBeFocused(); await page.keyboard.press('Enter');
  await expect(page.getByRole('button', { name: /^Choose starting branch/ })).toBeFocused(); await expect(page.getByRole('checkbox', { name: /Include local edits/ })).not.toBeChecked(); await expect(page.getByRole('checkbox', { name: /Include local edits/ })).toBeDisabled();
  await page.getByRole('button', { name: 'Continue', exact: true }).click(); await expect(page.getByRole('dialog')).toContainText('feature/refine-the-preview');
  await page.screenshot({ path: '.ui-audit/worktree-starting-review-desktop.png', animations: 'disabled' });
  const id = await create(page), detail = await (await request.get(`/api/sessions/${id}`)).json();
  expect(await readFile(join(detail.session.workspace, 'notes.md'), 'utf8')).toBe('Feature branch notes'); expect(await readFile(join(workspace, 'notes.md'), 'utf8')).toBe('Current local work'); expect((await git('symbolic-ref', '--short', 'HEAD')).stdout.trim()).toBe('main');
});
test('refreshes a moved fetched starting point and keeps the picker usable on a narrow screen', async ({ page, request }) => {
  await page.setViewportSize({ width: 390, height: 650 }); await page.emulateMedia({ colorScheme: 'light' });
  await git('update-ref', 'refs/remotes/origin/design', 'HEAD'); await git('commit', '--allow-empty', '-m', 'Newer commit');
  await open(page); await page.getByRole('button', { name: 'New worktree', exact: true }).click(); await page.getByRole('textbox', { name: 'Worktree task name' }).fill('A fresh starting point');
  await page.getByRole('button', { name: /^Choose starting branch/ }).click(); await page.getByRole('textbox', { name: 'Search starting branches' }).fill('origin/design');
  await expect(page.getByRole('option', { name: /origin\/design/ })).toBeVisible(); await page.getByRole('textbox', { name: 'Search starting branches' }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: '.ui-audit/worktree-starting-picker-mobile.png', animations: 'disabled' });
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog', { name: 'New worktree', exact: true })).toBeVisible(); await expect(page.getByRole('button', { name: /^Choose starting branch/ })).toBeFocused();
  await page.keyboard.press('ArrowDown'); await page.getByRole('textbox', { name: 'Search starting branches' }).fill('origin/design'); await page.keyboard.press('Enter');
  await page.getByRole('button', { name: 'Continue', exact: true }).click(); await expect(page.getByRole('dialog', { name: 'Create worktree?' })).toBeVisible();
  await git('update-ref', 'refs/remotes/origin/design', 'HEAD'); await page.getByRole('button', { name: 'Create and open', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('starting branch moved');
  await page.getByRole('button', { name: 'Refresh review', exact: true }).click(); await expect(page.getByRole('alert')).toHaveCount(0); await expect(page.getByRole('button', { name: 'Create and open', exact: true })).toBeFocused();
  await page.screenshot({ path: '.ui-audit/worktree-starting-review-mobile.png', animations: 'disabled' }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const id = await create(page), detail = await (await request.get(`/api/sessions/${id}`)).json(); expect(detail.session.worktree.head).toBe((await git('rev-parse', 'HEAD')).stdout.trim());
});

test('continues a worktree conversation locally with files, staging, draft and browser tabs intact', async ({ page, request }) => {
  await page.emulateMedia({ colorScheme: 'dark' }); await open(page); await review(page, 'Continue locally'); const id = await create(page);
  const initial = await (await request.get(`/api/sessions/${id}`)).json(), source = initial.session.workspace, originalMain = (await git('rev-parse', 'main')).stdout;
  await writeFile(join(source, 'notes.md'), '# Committed worktree idea\n'); await exec('git', ['add', '.'], { cwd: source }); await exec('git', ['commit', '-m', 'Keep idea'], { cwd: source });
  const composer = page.getByRole('textbox', { name: 'Message Litespeed' }); await composer.fill('create fixture inside the worktree'); await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await page.getByRole('region', { name: 'Permission requested' }).getByRole('button', { name: 'Allow once', exact: true }).click();
  await expect.poll(async () => (await (await request.get(`/api/sessions/${id}`)).json()).session.status).toBe('idle');
  await exec('git', ['add', 'result.txt'], { cwd: source }); await writeFile(join(source, 'notes.md'), '# Ready to continue locally\n');
  const sourceStatus = (await exec('git', ['status', '--porcelain=v1'], { cwd: source })).stdout, messages = (await (await request.get(`/api/sessions/${id}`)).json()).messages;
  await composer.fill('Keep my next step with this task');
  const settings = await (await request.get('/api/settings')).json(), url = settings.providers.find((provider: { id: string }) => provider.id === 'fixture').baseUrl + '/browser-inspector';
  expect((await request.post(`/api/sessions/${id}/browser`, { data: { action: 'open', url } })).ok()).toBe(true);
  const browserBefore = await (await request.get(`/api/sessions/${id}/browser`)).json();
  await page.getByRole('tab', { name: 'Files', exact: true }).click(); await page.getByRole('button', { name: 'Browse files', exact: true }).click();
  await page.locator('.file-list').getByRole('button', { name: 'notes.md', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Ready to continue locally' })).toBeVisible();
  const requestsBefore = (await (await request.get('/fixture/requests')).json()).count;
  await page.getByRole('button', { name: 'Session actions', exact: true }).click(); await page.getByRole('button', { name: 'Continue locally', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Continue in the local project?', exact: true });
  await expect(dialog.getByRole('button', { name: 'Continue locally', exact: true })).toBeFocused();
  await page.screenshot({ path: '.ui-audit/task-local-review-desktop.png', animations: 'disabled' });
  await dialog.getByRole('button', { name: 'Continue locally', exact: true }).click(); await expect(dialog).toHaveCount(0);
  await expect(composer).toHaveValue('Keep my next step with this task'); await expect(composer).toBeFocused();
  await expect(page.getByRole('button', { name: 'Manage task worktree', exact: true })).toHaveCount(0); await expect(page).toHaveURL(new RegExp(`#session/${id}$`));
  await expect(page.getByRole('tab', { name: 'notes.md', exact: true })).toHaveAttribute('aria-selected', 'true'); await expect(page.getByRole('heading', { name: 'Ready to continue locally' })).toBeVisible();
  const moved = await (await request.get(`/api/sessions/${id}`)).json(); expect(moved.session.workspace).toBe(workspace); expect(moved.messages.slice(0, -1)).toEqual(messages);
  expect((await git('rev-parse', 'main')).stdout).toBe(originalMain); expect((await exec('git', ['status', '--porcelain=v1'], { cwd: source })).stdout).toBe(sourceStatus);
  expect(await readFile(join(workspace, 'notes.md'), 'utf8')).toBe('# Ready to continue locally\n'); expect((await git('show', ':result.txt')).stdout).toBe(await readFile(join(source, 'result.txt'), 'utf8'));
  expect((await (await request.get('/fixture/requests')).json()).count).toBe(requestsBefore);
  const browserAfter = await (await request.get(`/api/sessions/${id}/browser`)).json(); expect(browserAfter.tabs.map((tab: { id: string; url: string }) => [tab.id, tab.url])).toEqual(browserBefore.tabs.map((tab: { id: string; url: string }) => [tab.id, tab.url]));
  await page.getByRole('button', { name: 'Session actions', exact: true }).click(); await expect(page.getByRole('button', { name: 'Undo last turn', exact: true })).toBeDisabled(); await page.getByRole('button', { name: 'Close session actions', exact: true }).click();
  await page.screenshot({ path: '.ui-audit/task-local-moved-desktop.png', animations: 'disabled' });
  await page.getByRole('tab', { name: 'result.txt', exact: true }).click();
  await composer.fill(`RULES_BROWSER READ_PATH[${workspace}/notes.md]`); await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await expect(page.getByRole('tab', { name: 'notes.md', exact: true })).toHaveAttribute('aria-selected', 'true');
  await expect.poll(async () => (await (await request.get(`/api/sessions/${id}`)).json()).session.status).toBe('idle');
  await composer.fill('The local draft also survives a reload'); await page.reload(); await expect(composer).toHaveValue('The local draft also survives a reload');
  await expect(page.getByRole('tab', { name: 'notes.md', exact: true })).toHaveAttribute('aria-selected', 'true');
});

test('refreshes local continuation after a new local edit without overwriting that edit', async ({ page, request }) => {
  await page.setViewportSize({ width: 390, height: 500 }); await page.emulateMedia({ colorScheme: 'light' }); await open(page); await review(page, 'Mobile local continuation'); const id = await create(page);
  const source = (await (await request.get(`/api/sessions/${id}`)).json()).session.workspace;
  await page.getByRole('textbox', { name: 'Message Litespeed' }).fill('Keep this draft during review');
  await page.getByRole('button', { name: 'Session actions', exact: true }).click(); await page.getByRole('button', { name: 'Continue locally', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Continue in the local project?', exact: true }), proceed = dialog.getByRole('button', { name: 'Continue locally', exact: true });
  await expect(proceed).toBeFocused(); await expect(proceed).toBeInViewport();
  await expect(dialog.locator('.worktrees-intro')).toBeInViewport({ ratio: 1 });
  await writeFile(join(workspace, 'notes.md'), '# A newer local edit\n');
  await proceed.click(); await expect(dialog.getByRole('alert')).toContainText('local project has changes'); await expect(dialog.getByRole('button', { name: 'Refresh review', exact: true })).toBeFocused();
  expect(await readFile(join(workspace, 'notes.md'), 'utf8')).toBe('# A newer local edit\n'); expect((await (await request.get(`/api/sessions/${id}`)).json()).session.workspace).toBe(source);
  await writeFile(join(workspace, 'notes.md'), '# A quiet workspace\n'); await dialog.getByRole('button', { name: 'Refresh review', exact: true }).click(); await expect(proceed).toBeFocused();
  await expect(dialog.locator('.worktrees-intro')).toBeInViewport({ ratio: 1 }); await expect(proceed).toBeInViewport({ ratio: 1 });
  await page.screenshot({ path: '.ui-audit/task-local-review-mobile.png', animations: 'disabled' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await proceed.click(); await expect(dialog).toHaveCount(0); await expect(page.getByRole('textbox', { name: 'Message Litespeed' })).toHaveValue('Keep this draft during review');
});

test('explains an unavailable local destination and returns focus when dismissed', async ({ page, request }) => {
  await open(page); await review(page, 'Keep separate'); const id = await create(page), source = (await (await request.get(`/api/sessions/${id}`)).json()).session.workspace;
  await writeFile(join(workspace, 'untracked.txt'), 'Do not replace this');
  await page.getByRole('button', { name: 'Session actions', exact: true }).click(); await page.getByRole('button', { name: 'Continue locally', exact: true }).click();
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('local project has changes');
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page.getByRole('button', { name: 'Session actions', exact: true })).toBeFocused();
  expect((await (await request.get(`/api/sessions/${id}`)).json()).session.workspace).toBe(source); expect(await readFile(join(workspace, 'untracked.txt'), 'utf8')).toBe('Do not replace this');
});
