/** Real PTY acceptance suite. The fixture owns an ephemeral server and workspace;
 * no user sessions, configuration, credentials, or provider quota are touched. */
import { spawn } from 'node:child_process';
import { mkdir, writeFile, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { once } from 'node:events';
import assert from 'node:assert/strict';
import pty from 'node-pty';
import xterm from '@xterm/headless';
import { fusionCases } from './tui-fusion-cases.mjs';

const root = resolve(import.meta.dirname, '..');
const artifacts = join(root, 'test-results-tui');
await mkdir(artifacts, { recursive: true });
const localConfig = await mkdtemp(join(tmpdir(), 'litespeed-tui-test-'));
const server = spawn(process.execPath, ['--import', 'tsx', 'scripts/e2e-server.ts'], { cwd: root, env: { ...process.env, LITESPEED_E2E_PORT: '0', LITESPEED_E2E_NO_VITE: '1' }, stdio: ['ignore', 'pipe', 'pipe'] });
let log = '', terminal, exit, raw = '', emulator;
server.stdout.on('data', data => { log += data; });
server.stderr.on('data', data => { log += data; });
const waitFor = async (condition, label, timeout = 15000) => {
  const deadline = Date.now() + timeout;
  while (Date.now() < deadline) { if (await condition()) return; await new Promise(done => setTimeout(done, 60)); }
  throw new Error(`Timed out: ${label}\n${screen()}\n${log.slice(-2000)}`);
};
const screen = () => emulator ? Array.from({ length: emulator.rows }, (_, row) => emulator.buffer.active.getLine(emulator.buffer.active.viewportY + row)?.translateToString(true, 0, emulator.cols) ?? '').join('\n') : '';
const save = async name => writeFile(join(artifacts, `${name}.txt`), screen());
try {
  await waitFor(() => /ready at (http:\/\/\S+)/.test(log), 'fixture ready');
  const base = log.match(/ready at (http:\/\/\S+)/)[1];
  const api = async (path, body, method) => {
    const response = await fetch(`${base}/api${path}`, { method: method ?? (body === undefined ? 'GET' : 'POST'), ...(body === undefined ? {} : { headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }) });
    const data = await response.json(); if (!response.ok) throw new Error(JSON.stringify(data)); return data;
  };
  const settings = await api('/settings');
  await mkdir(join(settings.workspace, '.litespeed', 'commands'), { recursive: true });
  await writeFile(join(settings.workspace, '.litespeed', 'commands', 'terminal-review.md'), 'Review $1; arguments: $ARGUMENTS');
  await mkdir(join(settings.workspace, '.litespeed', 'skills', 'verification'), { recursive: true });
  await writeFile(join(settings.workspace, '.litespeed', 'profiles.json'), JSON.stringify({ version: 1, profiles: [], skills: [{ id: 'verification', name: 'Verification checklist', description: 'Verify changes.' }] }));
  await writeFile(join(settings.workspace, '.litespeed', 'skills', 'verification', 'SKILL.md'), 'SKILL_TERMINAL_PINNED: verify before reporting success.');
  const editorPath = join(localConfig, 'editor.sh');
  await writeFile(editorPath, '#!/bin/sh\nprintf \"%s\" \"Draft returned from external editor\" > \"$1\"\n');
  const session = await api('/sessions', { workspace: settings.workspace, permissionMode: 'ask' });
  const detail = () => api(`/sessions/${session.id}`);
  emulator = new xterm.Terminal({ cols: 100, rows: 32, allowProposedApi: true });
  const launch = () => {
  emulator.reset(); emulator.resize(100, 32);
  terminal = pty.spawn(process.execPath, ['bin/litespeed.mjs', 'tui', '--url', base, '--session', session.id, '--workspace', settings.workspace], { cwd: root, cols: 100, rows: 32, name: 'xterm-256color', env: { ...process.env, TERM: 'xterm-256color', SHELL: '/bin/sh', VISUAL: `/bin/sh '${editorPath}'`, LITESPEED_DISABLE_PROJECT_CONFIG: '1', LITESPEED_CONFIG_DIR: localConfig, XDG_CONFIG_HOME: localConfig, XDG_STATE_HOME: localConfig } });
  exit = new Promise(resolve => terminal.onExit(resolve));
  terminal.onData(data => { raw += data; emulator.write(data); });
  };
  launch();
  await waitFor(() => screen().includes('Commands [Ctrl+P]'), 'composer ready');
  await save('01-ready');
  // Let the initial editor focus settle before injecting a command through the PTY.
  await new Promise(done => setTimeout(done, 200));
  terminal.write('/skills\r');
  await waitFor(() => screen().includes('Skills for this session') && screen().includes('Verification checklist'), 'skill browser');
  terminal.write('\r');
  await waitFor(() => screen().includes('☑ Verification'), 'skill selected');
  terminal.write('Use skills');
  await waitFor(() => screen().includes('› Use skills'), 'filter apply skills');
  terminal.write('\r');
  await waitFor(async () => (await detail()).session.profile?.skillIds.includes('verification'), 'browser pins skill');
  assert.equal((await detail()).messages.length, 0, 'skill selection starts no model turn');
  await waitFor(() => !screen().includes('Skills for this session'), 'skill browser closed');
  terminal.write('/skills\r');
  await waitFor(() => screen().includes('☑ Verification'), 'active skill shown');
  terminal.write('\rUse skills');
  await waitFor(() => screen().includes('› Use skills'), 'filter removal apply');
  terminal.write('\r');
  await waitFor(async () => !(await detail()).session.profile, 'browser removes skill');
  await waitFor(() => !screen().includes('Skills for this session'), 'removal browser closed');
  terminal.write('/verification');
  await waitFor(() => screen().includes('Use skill: Verification') && screen().includes('Tab/Enter complete'), 'skill autocomplete loaded');
  terminal.write('\r');
  await waitFor(() => screen().includes('/verification') && !screen().includes('Tab/Enter complete'), 'skill reference stays in composer');
  assert.equal((await detail()).messages.length, 0, 'autocomplete does not send a request');
  assert(!(await detail()).session.profile, 'autocomplete does not pin a session skill');
  terminal.write('PROFILE_BROWSER skill check\r');
  await waitFor(async () => (await (await fetch(`${base}/fixture/profiles`)).json()).requests.length > 0 && (await detail()).session.status === 'idle', 'message invokes skill');
  assert(JSON.stringify((await (await fetch(`${base}/fixture/profiles`)).json()).requests).includes('SKILL_TERMINAL_PINNED'), 'skill body reaches model context');
  assert.equal((await detail()).messages.find(message => message.role === 'user').content, '/verification PROFILE_BROWSER skill check', 'short invocation stays visible in history');
  assert(!(await detail()).session.profile, 'invocation leaves session-wide selection alone');
  await waitFor(() => screen().includes('idle') && screen().includes('Ask Litespeed to do'), 'skill turn idle composer');
  await save('01-skills');
  terminal.write('create fixture\r');
  await waitFor(() => screen().includes('1 Allow once'), 'approval prompt');
  assert.equal((await detail()).session.status, 'waiting');
  await save('02-permission');
  terminal.write('\x06');
  await waitFor(() => screen().includes('Review · Driver wants to write a file'), 'approval preview');
  await save('02-permission-preview');
  terminal.write('\x1b');
  await waitFor(() => !screen().includes('Review · Driver wants to write a file'), 'close approval preview');
  terminal.write('1');
  await waitFor(async () => (await detail()).session.status === 'idle', 'approved write completes');
  assert((await api(`/sessions/${session.id}/changes`)).changes?.length > 0, 'approved change is reviewable');
  await waitFor(() => screen().includes('idle') && screen().includes('Ask Litespeed to do'), 'idle composer');
  terminal.write('ask fixture question\r');
  await waitFor(() => screen().includes('Which storage'), 'question prompt');
  await save('03-question');
  terminal.write('0');
  await waitFor(() => screen().includes('Your answer'), 'custom answer input');
  terminal.write('Use an embedded database\r');
  await waitFor(async () => (await detail()).session.status === 'idle', 'custom answer completes');
  await waitFor(() => screen().includes('idle') && screen().includes('Ask Litespeed to do'), 'composer after custom answer');
  terminal.write('slow response\r');
  await waitFor(async () => (await detail()).session.status === 'running', 'running response');
  terminal.write('\x1b');
  await waitFor(async () => (await detail()).session.status === 'idle', 'single escape interrupts', 2000);
  terminal.write('\x10');
  await waitFor(() => screen().includes('Choose models') && screen().includes('Search…'), 'command palette');
  await save('04-commands');
  terminal.write('\x1b');
  await new Promise(done => setTimeout(done, 200));
  terminal.write('/models\r');
  await waitFor(() => screen().includes('Architecture: Single model'), 'model settings');
  terminal.write('\r');
  await waitFor(() => screen().includes('Expert Fusion'), 'five architecture choices');
  await save('05-architectures');
  terminal.write('\x1b[B\x1b[B\x1b[B\r');
  await waitFor(() => screen().includes('Worker: Choose a model'), 'team roles');
  terminal.write('\x1b[H\x1b[B\x1b[B\x1b[B\r');
  await waitFor(() => screen().includes('Enter a model ID'), 'worker model search');
  terminal.write('test-fast');
  await waitFor(() => screen().includes('› test-fast'), 'filtered worker');
  terminal.write('\r');
  await waitFor(() => screen().includes('Worker: test-fast'), 'worker selected');
  terminal.write('\x1b[F\x1b[A\r');
  await waitFor(async () => (await detail()).session.architecture?.worker?.model === 'test-fast', 'architecture saved');
  await api(`/sessions/${session.id}`, { architecture: null, expectedConfigRevision: (await detail()).session.configRevision }, 'PATCH');
  await waitFor(() => screen().includes('Commands [Ctrl+P]') && !screen().includes('Save applies'), 'back to composer');
  terminal.write('/settings\r');
  await waitFor(() => screen().includes('Project profiles'), 'settings sections');
  await save('06-settings');
  terminal.write('\x1b[B\x1b[B\x1b[B\r');
  await waitFor(() => screen().includes('+ Create profile'), 'project profiles');
  terminal.write('\x1b[F\x1b[A\r');
  await waitFor(() => screen().includes('Name: Choose a name'), 'new profile form');
  terminal.write('\r');
  await waitFor(() => screen().includes('Profile name'), 'profile name prompt');
  terminal.write('Terminal reviewer\r');
  await waitFor(() => screen().includes('Name: Terminal reviewer'), 'profile name saved locally');
  terminal.write('\x1b[H\x1b[B\x1b[B\r');
  await waitFor(() => screen().includes('Profile instructions'), 'profile instructions prompt');
  terminal.write('Review changes and report concrete problems.');
  await new Promise(done => setTimeout(done, 120)); terminal.write('\x13');
  await waitFor(() => screen().includes('Save profile'), 'profile ready to save');
  terminal.write('\x1b[F\r');
  await waitFor(async () => (await api(`/profiles?workspace=${encodeURIComponent(settings.workspace)}`)).profiles.some(profile => profile.id === 'terminal-reviewer'), 'profile saved through TUI');
  await waitFor(() => screen().includes('● No profile') && screen().includes('○ Terminal reviewer'), 'profile catalog refreshed');
  terminal.write('\x1b[H\x1b[B\r');
  await waitFor(() => screen().includes('Edit Terminal reviewer'), 'profile selected');
  terminal.write('\x1b[H\x1b[B\x1b[B\x1b[B\x1b[B\r');
  await waitFor(async () => (await detail()).session.profile?.profileId === 'terminal-reviewer', 'profile applied');
  await save('07-profile');
  terminal.write('\x1b');
  await new Promise(done => setTimeout(done, 100));
  await api(`/sessions/${session.id}/profile`, { expectedConfigRevision: (await detail()).session.configRevision ?? 0, choice: { profileId: null, skillIds: [] } });
  terminal.write('@hello');
  await new Promise(done => setTimeout(done, 120)); terminal.write('\t');
  await waitFor(() => screen().includes('Matching files'), 'file reference search');
  terminal.write('\r');
  await waitFor(() => screen().includes('hello.ts') && !screen().includes('Matching files'), 'file attached');
  terminal.write('Review the attached source\r');
  await waitFor(async () => (await detail()).messages.some(message => message.role === 'user' && message.attachments?.some(file => file.path === 'src/hello.ts' && file.content?.includes('world'))), 'file snapshot accepted');
  await waitFor(() => screen().includes('idle') && screen().includes('Ask Litespeed to do'), 'attachment response completes');
  terminal.write('create fixture denied\r');
  await waitFor(() => screen().includes('1 Allow once'), 'deny approval prompt');
  terminal.write('3');
  await waitFor(async () => (await detail()).messages.some(message => message.toolCalls?.some(call => call.status === 'denied')), 'denied tool recorded');
  await waitFor(() => screen().includes('idle') && screen().includes('Ask Litespeed to do'), 'denied turn settles');
  terminal.write('create fixture always\r');
  await waitFor(() => screen().includes('1 Allow once'), 'always approval prompt');
  terminal.write('2');
  await waitFor(async () => (await api(`/sessions/${session.id}/tool-grants`)).tools.includes('write_file'), 'always grant recorded');
  await waitFor(() => screen().includes('idle') && screen().includes('Ask Litespeed to do'), 'always turn settles');
  const written = (await api(`/file?workspace=${encodeURIComponent(settings.workspace)}&path=result.txt`)).content;
  terminal.write('/undo\r');
  await waitFor(async () => (await detail()).history.canRedo, 'undo from terminal');
  assert.notEqual((await api(`/file?workspace=${encodeURIComponent(settings.workspace)}&path=result.txt`)).content, written);
  await waitFor(() => !screen().includes('Undoing history'), 'undo accepted');
  terminal.write('/redo\r');
  await waitFor(async () => (await api(`/file?workspace=${encodeURIComponent(settings.workspace)}&path=result.txt`)).content === written, 'redo restores file');
  await api(`/sessions/${session.id}/queue/pause`, {});
  terminal.write('slow response queue test\r');
  await waitFor(() => screen().includes('Queue a follow-up'), 'queue test running');
  terminal.write('queued follow-up\r');
  await waitFor(async () => (await detail()).queue.items.length === 1, 'follow-up queued');
  assert(screen().includes('queued follow-up')&&screen().includes('Steer now'),'queued content and direct steering stay visible');
  assert(screen().includes('Queue [Enter] · Steer [Alt+Enter]'),'running composer accurately labels both actions');
  terminal.write('\x1b');
  await waitFor(() => screen().includes('idle') && screen().includes('Press Up to edit') && !screen().includes('Interrupting'), 'queue task stopped');
  terminal.write('/queue\r');
  await waitFor(() => screen().includes('Resume queue'), 'queue manager');
  terminal.write('\r');
  await waitFor(async () => (await detail()).queue.items.length === 0, 'queue resumed');
  await waitFor(() => screen().includes('idle') && screen().includes('Ask Litespeed to do'), 'queued turn completes');
  await api(`/sessions/${session.id}/queue/pause`, {});
  await api(`/sessions/${session.id}/queue`, { content: 'remove this queued message' });
  await waitFor(() => screen().includes('1 queued'), 'queued item visible');
  terminal.write('/queue\r');
  await waitFor(() => screen().includes('remove this queued message'), 'removable queued item');
  terminal.write('\x1b[B\r');
  await waitFor(() => screen().includes('Steer driver now'), 'queued message actions');
  terminal.write('\x1b[B\x1b[B\r');
  await waitFor(async () => (await detail()).queue.items.length === 0, 'queued item removed');
  await waitFor(() => screen().includes('Ask Litespeed to do'), 'composer after queue removal');
  await waitFor(() => !screen().includes('×') && !screen().includes('Updating queue') && screen().includes('Ask Litespeed to do'), 'queue action finished');
  terminal.write('slow response steering fixture');
  await waitFor(() => screen().includes('slow response steering fixture') && screen().includes('Send [Enter]'), 'steering task ready to send');
  terminal.write('\r');
  await waitFor(() => screen().includes('Queue a follow-up'), 'steering target running');
  terminal.write('driver steering from terminal');
  await waitFor(() => screen().includes('driver steering from terminal'), 'steering draft ready');
  terminal.write('\x10'); await waitFor(() => screen().includes('Search…') && screen().includes('Choose models'), 'steering palette');
  terminal.write('Send draft as steering\r');
  await waitFor(async () => (await detail()).messages.some(message => message.role === 'system' && message.content.startsWith('[Steering]') && message.content.endsWith('driver steering from terminal')), 'steering reaches driver');
  await waitFor(() => !screen().includes('×'), 'steering palette closed');
  await waitFor(() => {
    const contents = screen();
    return contents.includes('Queue a follow-up') && contents.split('\n').some(line => line.includes('┃') && line.includes('driver steering from terminal'));
  }, 'steering note renders in the user message rail after the composer clears');
  assert(!screen().includes('[Steering]') && !screen().includes('You · update'), 'steering has no internal wrapper or extra identity label');
  await save('steering-user-message');
  terminal.write('\x1b');
  await waitFor(() => screen().includes('idle') && screen().includes('Ask Litespeed to do'), 'steered task stops');
  await fusionCases({ api, terminal, screen, waitFor, save, settings, session, detail });
  terminal.write('/terminal-review "source files" tests\r');
  await waitFor(async () => (await detail()).messages.some(message => message.role === 'user' && message.content === 'Review source files; arguments: "source files" tests'), 'project template expanded');
  await waitFor(() => screen().includes('idle') && screen().includes('Ask Litespeed to do'), 'project command settles');
  terminal.write('/goal\r');
  await waitFor(() => screen().includes('New objective'), 'goal editor'); terminal.write('\r');
  await waitFor(() => screen().includes('Goal objective'), 'goal text field');
  terminal.write('Finish this fixture objective'); await new Promise(done => setTimeout(done, 120)); terminal.write('\x13');
  await waitFor(() => screen().includes('Set goal'), 'goal ready to save'); terminal.write('\x1b[F\r');
  await waitFor(async () => (await detail()).session.goal?.status === 'active', 'goal saved');
  await waitFor(() => screen().includes('Clear goal'), 'goal can be cleared'); terminal.write('\x1b[H\x1b[B\r');
  await waitFor(async () => (await detail()).session.goal?.status === 'cleared', 'goal cleared');
  terminal.write('\x1b'); await waitFor(() => !screen().includes('×'), 'goal editor closed');
  terminal.write('/editor\r');
  await waitFor(() => screen().includes('Draft returned from external editor'), 'external editor restores draft');
  assert(!(await detail()).messages.some(message => message.content === 'Draft returned from external editor'), 'editing does not submit');
  terminal.write('\r');
  await waitFor(async () => (await detail()).messages.some(message => message.role === 'user' && message.content === 'Draft returned from external editor'), 'editor draft sent');
  await waitFor(() => screen().includes('idle') && screen().includes('Ask Litespeed to do'), 'edited turn settles');
  terminal.write('/shell\r');
  await waitFor(() => screen().includes('Litespeed shell'), 'shell owns terminal');
  terminal.write('printf \"shell handoff verified\\n\"; exit\r');
  await waitFor(() => screen().includes('Commands [Ctrl+P]') && screen().includes('Ask Litespeed to do'), 'shell returns terminal to composer');
  // Bracketed paste retains Unicode and newlines without sending on newline.
  const beforePaste = (await detail()).messages.length;
  terminal.write('\x1b[200~Hello 世界 👩🏽‍💻\nSecond pasted line\x1b[201~');
  await waitFor(() => screen().includes('Second pasted line'), 'multiline paste renders');
  assert.equal((await detail()).messages.length, beforePaste);
  terminal.write('\r');
  await waitFor(async () => (await detail()).messages.some(message => message.role === 'user' && message.content.includes('Hello 世界 👩🏽‍💻\nSecond pasted line')), 'Unicode paste sent intact');
  await waitFor(() => screen().includes('idle') && screen().includes('Ask Litespeed to do'), 'paste turn settles');
  terminal.write('unfinished draft');
  await waitFor(() => screen().includes('unfinished draft'), 'draft typed');
  terminal.write('\x18'); await new Promise(done => setTimeout(done, 100)); terminal.write('l');
  await waitFor(() => screen().includes('Showing this project'), 'sessions picker');
  terminal.write('\r');
  await waitFor(async () => (await api('/sessions')).sessions.length === 2, 'new session created');
  await waitFor(() => screen().includes('A fresh start.'), 'new session opened');
  terminal.write('\x18'); await new Promise(done => setTimeout(done, 100)); terminal.write('l');
  await waitFor(() => screen().includes('Showing this project'), 'session switching');
  terminal.write('PROFILE_BROWSER');
  await waitFor(() => screen().includes('› /verification PROFILE_BROWSER'), 'original session filtered');
  terminal.write('\r');
  await waitFor(() => screen().includes('unfinished draft') && !screen().includes('Showing this project'), 'draft restored after switching');
  terminal.resize(140, 40); emulator.resize(140, 40);
  await new Promise(done => setTimeout(done, 250)); await save('08-wide');
  terminal.resize(80, 12); emulator.resize(80, 12);
  await new Promise(done => setTimeout(done, 250)); await save('09-short');
  assert(screen().includes('Commands [Ctrl+P]'), 'short terminal keeps controls visible');
  terminal.resize(80, 24); emulator.resize(80, 24);
  await new Promise(done => setTimeout(done, 300)); await save('05-small');
  terminal.write('\x03'); await new Promise(done => setTimeout(done, 100)); terminal.write('\x03');
  const status = await Promise.race([exit, new Promise((_, reject) => setTimeout(() => reject(new Error('Terminal did not exit')), 5000))]);
  assert.equal(status.exitCode, 0);
  launch();
  await waitFor(() => screen().includes('unfinished draft') && screen().includes('Commands [Ctrl+P]'), 'draft restored after process restart');
  terminal.write('\x03'); await new Promise(done => setTimeout(done, 100)); terminal.write('\x03');
  assert.equal((await exit).exitCode, 0);
  console.log('TUI PTY passed: drafts, send, approval preview/allow/always/deny, questions, steering, family cancellation, queue, history, four architectures, planner, profiles, goals, references, Unicode paste, editor, shell, sessions, restart, resize, and clean exit.');
} finally {
  try { await mkdir(artifacts, { recursive: true }); await save('last-screen'); await writeFile(join(artifacts, 'terminal.ansi'), raw); } catch { /* Cleanup must run even if artifact writing fails. */ }
  terminal?.kill(); emulator?.dispose();
  server.kill('SIGTERM');
  await Promise.race([once(server, 'exit'), new Promise(done => setTimeout(done, 3000))]);
  if (server.exitCode === null) server.kill('SIGKILL');
  await rm(localConfig, { recursive: true, force: true });
}
