/** Default keybinding table for the terminal client: one leader plus every
 * bindable action, each mapping to a command name. Users override entries in
 * litespeed-tui.json(c) under `keybinds`; an override fully replaces that action's
 * chord list. `false` or "none" disables an action. */

export interface KeyStroke {
  name: string;
  ctrl?: boolean;
  shift?: boolean;
  meta?: boolean;
  super?: boolean;
  hyper?: boolean;
}

export interface BindingObject {
  key: string | KeyStroke;
  event?: 'press' | 'release';
  preventDefault?: boolean;
  fallthrough?: boolean;
  [extra: string]: unknown;
}

export type BindingItem = string | KeyStroke | BindingObject;
export type BindingValue = false | 'none' | BindingItem | BindingItem[];

export const LEADER_DEFAULT = 'ctrl+x';
export const LEADER_TIMEOUT_DEFAULT = 2000;

/** action → default chord(s). "none" means bindable but unbound by default. */
export const KEYBIND_DEFAULTS: Record<string, BindingValue> = {
  leader: LEADER_DEFAULT,
  // App / global
  app_exit: 'ctrl+c,ctrl+d,<leader>q',
  app_debug: 'none',
  app_console: 'none',
  app_heap_snapshot: 'none',
  app_toggle_animations: 'none',
  app_toggle_file_context: 'none',
  app_toggle_diffwrap: 'none',
  app_toggle_paste_summary: 'none',
  app_toggle_session_directory_filter: 'none',
  command_list: 'ctrl+p',
  permissions_open: 'f3',
  settings_open: 'f4',
  help_show: 'none',
  docs_open: 'none',
  // Diff viewer
  diff_open: 'none',
  diff_close: 'escape,q',
  diff_toggle: 'enter,space',
  diff_expand: 'right',
  diff_expand_all: 'E',
  diff_collapse: 'left',
  diff_switch_focus: 'tab',
  diff_next_hunk: ']',
  diff_previous_hunk: '[',
  diff_next_file: 'n',
  diff_previous_file: 'p',
  diff_toggle_file_tree: 'b',
  diff_single_patch: 's',
  diff_switch_source: 'd',
  diff_toggle_view: 'v',
  diff_help: '?',
  // Editor / theme / layout / status
  editor_open: '<leader>e',
  theme_list: '<leader>t',
  theme_switch_mode: 'none',
  theme_mode_lock: 'none',
  sidebar_toggle: '<leader>b',
  scrollbar_toggle: 'none',
  status_view: '<leader>s',
  debug_view: 'none',
  // Session
  session_export: '<leader>x',
  session_copy: 'none',
  session_move: 'none',
  session_new: '<leader>n',
  session_list: '<leader>l',
  session_timeline: '<leader>g',
  session_fork: 'none',
  session_rename: 'ctrl+r',
  session_delete: 'ctrl+d',
  session_share: 'none',
  session_unshare: 'none',
  session_interrupt: 'escape',
  session_background: 'ctrl+b',
  session_compact: '<leader>c',
  session_toggle_timestamps: 'none',
  session_toggle_generic_tool_output: 'none',
  session_queued_prompts: '<leader>p',
  session_child_first: '<leader>down',
  session_child_cycle: 'right',
  session_child_cycle_reverse: 'left',
  session_parent: 'up',
  session_pin_toggle: 'ctrl+f',
  session_quick_switch_1: '<leader>1',
  session_quick_switch_2: '<leader>2',
  session_quick_switch_3: '<leader>3',
  session_quick_switch_4: '<leader>4',
  session_quick_switch_5: '<leader>5',
  session_quick_switch_6: '<leader>6',
  session_quick_switch_7: '<leader>7',
  session_quick_switch_8: '<leader>8',
  session_quick_switch_9: '<leader>9',
  // Stash / model / provider / agent / variant
  stash_delete: 'ctrl+d',
  model_provider_list: 'ctrl+a',
  model_favorite_toggle: 'ctrl+f',
  model_list: '<leader>m',
  model_cycle_recent: 'f2',
  model_cycle_recent_reverse: 'shift+f2',
  model_cycle_favorite: 'none',
  model_cycle_favorite_reverse: 'none',
  mcp_list: 'none',
  provider_connect: 'none',
  console_org_switch: 'none',
  agent_list: '<leader>a',
  agent_cycle: 'tab',
  agent_cycle_reverse: 'shift+tab',
  variant_cycle: 'ctrl+t',
  variant_list: 'none',
  // Message navigation / display
  messages_page_up: 'pageup,ctrl+alt+b',
  messages_page_down: 'pagedown,ctrl+alt+f',
  messages_line_up: 'ctrl+alt+y',
  messages_line_down: 'ctrl+alt+e',
  messages_half_page_up: 'ctrl+alt+u',
  messages_half_page_down: 'ctrl+alt+d',
  messages_first: 'ctrl+g,home',
  messages_last: 'ctrl+alt+g,end',
  messages_next: 'none',
  messages_previous: 'none',
  messages_last_user: 'none',
  messages_copy: '<leader>y',
  messages_undo: '<leader>u',
  messages_redo: '<leader>r',
  messages_toggle_conceal: '<leader>h',
  tool_details: 'alt+o',
  display_thinking: 'none',
  // Prompt / workspace
  prompt_submit: 'none',
  prompt_editor_context_clear: 'none',
  prompt_skills: 'none',
  prompt_stash: 'none',
  prompt_stash_pop: 'none',
  prompt_stash_list: 'none',
  workspace_set: 'none',
  // Input / textarea editing (readline-ish)
  input_clear: 'ctrl+c',
  input_paste: { key: 'ctrl+v', preventDefault: false },
  input_submit: 'return',
  input_newline: 'shift+return,ctrl+return,alt+return,ctrl+j',
  input_move_left: 'left,ctrl+b',
  input_move_right: 'right,ctrl+f',
  input_move_up: 'up',
  input_move_down: 'down',
  input_select_left: 'shift+left',
  input_select_right: 'shift+right',
  input_select_up: 'shift+up',
  input_select_down: 'shift+down',
  input_line_home: 'ctrl+a',
  input_line_end: 'ctrl+e',
  input_select_line_home: 'ctrl+shift+a',
  input_select_line_end: 'ctrl+shift+e',
  input_visual_line_home: 'alt+a',
  input_visual_line_end: 'alt+e',
  input_select_visual_line_home: 'alt+shift+a',
  input_select_visual_line_end: 'alt+shift+e',
  input_buffer_home: 'home',
  input_buffer_end: 'end',
  input_select_buffer_home: 'shift+home',
  input_select_buffer_end: 'shift+end',
  input_delete_line: 'ctrl+shift+d',
  input_delete_to_line_end: 'ctrl+k',
  input_delete_to_line_start: 'ctrl+u',
  input_backspace: 'backspace,shift+backspace',
  input_delete: 'ctrl+d,delete,shift+delete',
  input_undo: 'ctrl+-,super+z',
  input_redo: 'ctrl+.,super+shift+z',
  input_word_forward: 'alt+f,alt+right,ctrl+right',
  input_word_backward: 'alt+b,alt+left,ctrl+left',
  input_select_word_forward: 'alt+shift+f,alt+shift+right',
  input_select_word_backward: 'alt+shift+b,alt+shift+left',
  input_delete_word_forward: 'alt+d,alt+delete,ctrl+delete',
  input_delete_word_backward: 'ctrl+w,ctrl+backspace,alt+backspace',
  input_select_all: 'super+a',
  history_previous: 'up',
  history_next: 'down',
  // Dotted names: dialogs / autocomplete / permission / plugins (self-mapping)
  'dialog.select.prev': 'up,ctrl+p',
  'dialog.select.next': 'down,ctrl+n',
  'dialog.select.page_up': 'pageup',
  'dialog.select.page_down': 'pagedown',
  'dialog.select.home': 'home',
  'dialog.select.end': 'end',
  'dialog.select.submit': 'return',
  'dialog.prompt.submit': 'return',
  'dialog.mcp.toggle': 'space',
  'dialog.move_session.new': 'ctrl+m',
  'dialog.move_session.delete': 'ctrl+d',
  'dialog.move_session.refresh': 'ctrl+r',
  'prompt.autocomplete.prev': 'up,ctrl+p',
  'prompt.autocomplete.next': 'down,ctrl+n',
  'prompt.autocomplete.hide': 'escape',
  'prompt.autocomplete.select': 'return',
  'prompt.autocomplete.complete': 'tab',
  'permission.prompt.fullscreen': 'ctrl+f',
  'plugins.toggle': 'space',
  'dialog.plugins.install': 'shift+i',
  // Terminal / tips / plugins / which-key
  terminal_suspend: 'ctrl+z',
  terminal_title_toggle: 'none',
  tips_toggle: '<leader>h',
  plugin_manager: 'none',
  plugin_install: 'none',
  which_key_toggle: 'ctrl+alt+k',
  which_key_layout_toggle: 'ctrl+alt+shift+k',
  which_key_pending_toggle: 'ctrl+alt+shift+p',
  which_key_group_previous: 'ctrl+alt+left,ctrl+alt+[',
  which_key_group_next: 'ctrl+alt+right,ctrl+alt+]',
  which_key_scroll_up: 'ctrl+alt+up,ctrl+alt+p',
  which_key_scroll_down: 'ctrl+alt+down,ctrl+alt+n',
  which_key_page_up: 'ctrl+alt+pageup',
  which_key_page_down: 'ctrl+alt+pagedown',
  which_key_home: 'ctrl+alt+home',
  which_key_end: 'ctrl+alt+end',
};

/** action → command name. Dotted actions self-map and are omitted here; the
 * lookup falls back to the action name itself. */
export const COMMAND_MAP: Record<string, string> = {
  app_exit: 'app.exit',
  app_debug: 'app.debug',
  app_console: 'app.console',
  app_heap_snapshot: 'app.heap_snapshot',
  app_toggle_animations: 'app.toggle.animations',
  app_toggle_file_context: 'app.toggle.file_context',
  app_toggle_diffwrap: 'app.toggle.diffwrap',
  app_toggle_paste_summary: 'app.toggle.paste_summary',
  app_toggle_session_directory_filter: 'app.toggle.session_directory_filter',
  command_list: 'command.palette.show',
  permissions_open: 'session.permissions',
  settings_open: 'app.settings',
  help_show: 'help.show',
  docs_open: 'docs.open',
  diff_open: 'diff.open',
  diff_close: 'diff.close',
  diff_toggle: 'diff.toggle',
  diff_expand: 'diff.expand',
  diff_expand_all: 'diff.expand_all',
  diff_collapse: 'diff.collapse',
  diff_switch_focus: 'diff.switch_focus',
  diff_next_hunk: 'diff.next_hunk',
  diff_previous_hunk: 'diff.previous_hunk',
  diff_next_file: 'diff.next_file',
  diff_previous_file: 'diff.previous_file',
  diff_toggle_file_tree: 'diff.toggle_file_tree',
  diff_single_patch: 'diff.single_patch',
  diff_switch_source: 'diff.switch_source',
  diff_toggle_view: 'diff.toggle_view',
  diff_help: 'diff.help',
  editor_open: 'prompt.editor',
  theme_list: 'theme.switch',
  theme_switch_mode: 'theme.switch_mode',
  theme_mode_lock: 'theme.mode.lock',
  sidebar_toggle: 'session.sidebar.toggle',
  scrollbar_toggle: 'session.toggle.scrollbar',
  status_view: 'litespeed.status',
  debug_view: 'litespeed.debug',
  session_export: 'session.export',
  session_copy: 'session.copy',
  session_move: 'session.move',
  session_new: 'session.new',
  session_list: 'session.list',
  session_timeline: 'session.timeline',
  session_fork: 'session.fork',
  session_rename: 'session.rename',
  session_delete: 'session.delete',
  session_share: 'session.share',
  session_unshare: 'session.unshare',
  session_interrupt: 'session.interrupt',
  session_background: 'session.background',
  session_compact: 'session.compact',
  session_toggle_timestamps: 'session.toggle.timestamps',
  session_toggle_generic_tool_output: 'session.toggle.generic_tool_output',
  session_queued_prompts: 'session.queued_prompts',
  session_child_first: 'session.child.first',
  session_child_cycle: 'session.child.next',
  session_child_cycle_reverse: 'session.child.previous',
  session_parent: 'session.parent',
  session_pin_toggle: 'session.pin.toggle',
  session_quick_switch_1: 'session.quick_switch.1',
  session_quick_switch_2: 'session.quick_switch.2',
  session_quick_switch_3: 'session.quick_switch.3',
  session_quick_switch_4: 'session.quick_switch.4',
  session_quick_switch_5: 'session.quick_switch.5',
  session_quick_switch_6: 'session.quick_switch.6',
  session_quick_switch_7: 'session.quick_switch.7',
  session_quick_switch_8: 'session.quick_switch.8',
  session_quick_switch_9: 'session.quick_switch.9',
  stash_delete: 'stash.delete',
  model_provider_list: 'model.dialog.provider',
  model_favorite_toggle: 'model.dialog.favorite',
  model_list: 'model.list',
  model_cycle_recent: 'model.cycle_recent',
  model_cycle_recent_reverse: 'model.cycle_recent_reverse',
  model_cycle_favorite: 'model.cycle_favorite',
  model_cycle_favorite_reverse: 'model.cycle_favorite_reverse',
  mcp_list: 'mcp.list',
  provider_connect: 'provider.connect',
  console_org_switch: 'console.org.switch',
  agent_list: 'agent.list',
  agent_cycle: 'agent.cycle',
  agent_cycle_reverse: 'agent.cycle.reverse',
  variant_cycle: 'variant.cycle',
  variant_list: 'variant.list',
  messages_page_up: 'session.page.up',
  messages_page_down: 'session.page.down',
  messages_line_up: 'session.line.up',
  messages_line_down: 'session.line.down',
  messages_half_page_up: 'session.half.page.up',
  messages_half_page_down: 'session.half.page.down',
  messages_first: 'session.first',
  messages_last: 'session.last',
  messages_next: 'session.message.next',
  messages_previous: 'session.message.previous',
  messages_last_user: 'session.messages_last_user',
  messages_copy: 'messages.copy',
  messages_undo: 'session.undo',
  messages_redo: 'session.redo',
  messages_toggle_conceal: 'session.toggle.conceal',
  tool_details: 'session.toggle.actions',
  display_thinking: 'session.toggle.thinking',
  prompt_submit: 'prompt.submit',
  prompt_editor_context_clear: 'prompt.editor_context.clear',
  prompt_skills: 'prompt.skills',
  prompt_stash: 'prompt.stash',
  prompt_stash_pop: 'prompt.stash.pop',
  prompt_stash_list: 'prompt.stash.list',
  workspace_set: 'workspace.set',
  input_clear: 'prompt.clear',
  input_paste: 'prompt.paste',
  input_submit: 'input.submit',
  input_newline: 'input.newline',
  input_move_left: 'input.move.left',
  input_move_right: 'input.move.right',
  input_move_up: 'input.move.up',
  input_move_down: 'input.move.down',
  input_select_left: 'input.select.left',
  input_select_right: 'input.select.right',
  input_select_up: 'input.select.up',
  input_select_down: 'input.select.down',
  input_line_home: 'input.line.home',
  input_line_end: 'input.line.end',
  input_select_line_home: 'input.select.line.home',
  input_select_line_end: 'input.select.line.end',
  input_visual_line_home: 'input.visual.line.home',
  input_visual_line_end: 'input.visual.line.end',
  input_select_visual_line_home: 'input.select.visual.line.home',
  input_select_visual_line_end: 'input.select.visual.line.end',
  input_buffer_home: 'input.buffer.home',
  input_buffer_end: 'input.buffer.end',
  input_select_buffer_home: 'input.select.buffer.home',
  input_select_buffer_end: 'input.select.buffer.end',
  input_delete_line: 'input.delete.line',
  input_delete_to_line_end: 'input.delete.to.line.end',
  input_delete_to_line_start: 'input.delete.to.line.start',
  input_backspace: 'input.backspace',
  input_delete: 'input.delete',
  input_undo: 'input.undo',
  input_redo: 'input.redo',
  input_word_forward: 'input.word.forward',
  input_word_backward: 'input.word.backward',
  input_select_word_forward: 'input.select.word.forward',
  input_select_word_backward: 'input.select.word.backward',
  input_delete_word_forward: 'input.delete.word.forward',
  input_delete_word_backward: 'input.delete.word.backward',
  input_select_all: 'input.select.all',
  history_previous: 'prompt.history.previous',
  history_next: 'prompt.history.next',
  terminal_suspend: 'terminal.suspend',
  terminal_title_toggle: 'terminal.title.toggle',
  tips_toggle: 'tips.toggle',
  plugin_manager: 'plugins.list',
  plugin_install: 'plugins.install',
  which_key_toggle: 'which-key.toggle',
  which_key_layout_toggle: 'which-key.layout.toggle',
  which_key_pending_toggle: 'which-key.pending.toggle',
  which_key_group_previous: 'which-key.group.previous',
  which_key_group_next: 'which-key.group.next',
  which_key_scroll_up: 'which-key.scroll.up',
  which_key_scroll_down: 'which-key.scroll.down',
  which_key_page_up: 'which-key.page.up',
  which_key_page_down: 'which-key.page.down',
  which_key_home: 'which-key.home',
  which_key_end: 'which-key.end',
};

export function commandForAction(action: string): string {
  return COMMAND_MAP[action] ?? action;
}

/** The managed-textarea command subset routed only when a textarea has focus. */
export const INPUT_COMMANDS = [
  'input.submit', 'input.newline',
  'input.move.left', 'input.move.right', 'input.move.up', 'input.move.down',
  'input.select.left', 'input.select.right', 'input.select.up', 'input.select.down',
  'input.line.home', 'input.line.end', 'input.select.line.home', 'input.select.line.end',
  'input.visual.line.home', 'input.visual.line.end',
  'input.select.visual.line.home', 'input.select.visual.line.end',
  'input.buffer.home', 'input.buffer.end', 'input.select.buffer.home', 'input.select.buffer.end',
  'input.delete.line', 'input.delete.to.line.end', 'input.delete.to.line.start',
  'input.backspace', 'input.delete', 'input.undo', 'input.redo',
  'input.word.forward', 'input.word.backward',
  'input.select.word.forward', 'input.select.word.backward',
  'input.delete.word.forward', 'input.delete.word.backward',
  'input.select.all',
] as const;
